// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk0Id6Sg92ELerdqVK-B0t62f3byNb0Kg',
    appId: '1:642587897248:web:b8b5864a90f2c2a8ee88c5',
    messagingSenderId: '642587897248',
    projectId: 'esp8266-project-ca7ef',
    authDomain: 'esp8266-project-ca7ef.firebaseapp.com',
    databaseURL: 'https://esp8266-project-ca7ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp8266-project-ca7ef.firebasestorage.app',
    measurementId: 'G-F2FVQRJFNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWzi2fYS23JAvy2mXUiKD5my5Ebh2yV80',
    appId: '1:642587897248:android:d78c9554d42ccb89ee88c5',
    messagingSenderId: '642587897248',
    projectId: 'esp8266-project-ca7ef',
    databaseURL: 'https://esp8266-project-ca7ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp8266-project-ca7ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUi594T2WACPpMVyOtstucZqUNNpvnyxk',
    appId: '1:642587897248:ios:867c8514920627abee88c5',
    messagingSenderId: '642587897248',
    projectId: 'esp8266-project-ca7ef',
    databaseURL: 'https://esp8266-project-ca7ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp8266-project-ca7ef.firebasestorage.app',
    iosBundleId: 'com.example.ledapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUi594T2WACPpMVyOtstucZqUNNpvnyxk',
    appId: '1:642587897248:ios:867c8514920627abee88c5',
    messagingSenderId: '642587897248',
    projectId: 'esp8266-project-ca7ef',
    databaseURL: 'https://esp8266-project-ca7ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp8266-project-ca7ef.firebasestorage.app',
    iosBundleId: 'com.example.ledapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk0Id6Sg92ELerdqVK-B0t62f3byNb0Kg',
    appId: '1:642587897248:web:71357fac481a2ab5ee88c5',
    messagingSenderId: '642587897248',
    projectId: 'esp8266-project-ca7ef',
    authDomain: 'esp8266-project-ca7ef.firebaseapp.com',
    databaseURL: 'https://esp8266-project-ca7ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp8266-project-ca7ef.firebasestorage.app',
    measurementId: 'G-MVZWPVE1S7',
  );
}
